package com.capstone.unwind.enums;

public enum WalletTransactionEnum {
    RENTALPOSTING,
    EXCHANGEPOSTING,
    RENTALREFUND,
    EXCHANGEREFUND,
    MEMBERSHIP,
    APPROVAL_RENTAL_POSTING,
    APPROVAL_REQUESTEXCHANGE,
    APPROVAL_EXCHANGEPOSTING,
    REJECT_EXCHANGEPOSTING,
    REJECT_RENTALPOSTING,
    REJECT_REQUESTEXCHANGE,
    DEPOSITMONEY

}
